package nz.ac.aut.prog2.CaveAdventure.Interface;

import java.applet.Applet;
import java.io.File;
import java.net.URI;
import java.net.URL;
import nz.ac.aut.prog2.CaveAdventure.UI.CaveAdventureUI;
import nz.ac.aut.prog2.CaveAdventure.model.CaveGame;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * The class is to show the introduction of the Cave Adventure to the player so
 * that player can easily understand the game.
 *
 * @author Yixiao Chen-1272398
 * @version 30/05/2013
 */
public class caveGameIntroduction extends javax.swing.JFrame {

    /**
     * Constructor of the caveGameIntroduction method Set the introduction in
     * the cente of the window
     */
    public caveGameIntroduction() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        playGame = new javax.swing.JButton();
        quitGame = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tips = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introduction");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane3.setBackground(null);
        jScrollPane3.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nThis game is called cave Adventure.\nThe game will include one player, \nsome items that can be carried,\nsome rocks will fall, some fatal and \nnon-fatal hazards and one detonates.\nYour aim is to survival in the cave \nworld.You will have 100 energy at\nthe beginning of the game. Every \nstep will  cost your 5 points energy. \nIf you fall into a hazard or the time is \nup after  you picking up the detonates,\nor rock fall on you. You will die and \nyou lose the game.\nTo win the game, you should collected\nall the two keys\nGood luck to you and enjoy.\n");
        jTextArea1.setBorder(null);
        jScrollPane3.setViewportView(jTextArea1);

        playGame.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        playGame.setText("Play Game");
        playGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameActionPerformed(evt);
            }
        });

        quitGame.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        quitGame.setText("Quit Game");
        quitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitGameActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(null);
        jScrollPane2.setBorder(null);

        tips.setBackground(new java.awt.Color(204, 204, 204));
        tips.setColumns(20);
        tips.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        tips.setRows(5);
        tips.setText("Tips:\n\n ۩      means Hazard\n ●o●  means The player\n ▄     means Item\n ۞      means detonate");
        jScrollPane2.setViewportView(tips);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playGame)
                    .addComponent(quitGame)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playGame)
                        .addGap(28, 28, 28)
                        .addComponent(quitGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is to quit the game
     *
     * @param evt to read the player's choice
     */
    private void quitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitGameActionPerformed
        dispose();
    }//GEN-LAST:event_quitGameActionPerformed

    /**
     * This method is to start the game
     *
     * @param evt to read the player's choice
     */
    private void playGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameActionPerformed
        CaveGame game = new CaveGame();
        final CaveAdventureUI ui = new CaveAdventureUI(game);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ui.setVisible(true);
            }
        });
       
        dispose();
    }//GEN-LAST:event_playGameActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton playGame;
    private javax.swing.JButton quitGame;
    private javax.swing.JTextArea tips;
    // End of variables declaration//GEN-END:variables
}
